
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class DibujaPrimitivasFrames extends javax.swing.JFrame {

    public static LinkedList<Integer> lista = new LinkedList<Integer>();

    public DibujaPrimitivasFrames() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }

    public void paint(Graphics g) {
        super.paint(g);
    }

    public void Graficar(int p) {
        Graphics2D g2d = (Graphics2D) getGraphics();
        String figuras = jComboBox1.getSelectedItem().toString();

        switch (figuras) {
            case "Escolha a estrutura de dados":
                JOptionPane.showMessageDialog(null, "Selecione uma estrutura");
                break;
            case "Lista simplesmente encadeada":
                int x = 150;
                int y = 150;

                System.out.println("LISTA: ");
                for (int i = 0; i < lista.size(); i++) {
                    if (i == p) {
                        System.out.print(lista.get(i) + " ");
                        g2d.setColor(Color.green);
                        g2d.draw(new Ellipse2D.Double(x, y, 50, 50));
                        g2d.fill(new Ellipse2D.Double(x, y, 50, 50));
                        g2d.drawString("P: " + (i+1), x + 15, y - 10);
                        g2d.setColor(Color.black);
                        g2d.drawString(lista.get(i) + "", x + 15, y + (50 / 2));

                    } else {
                        System.out.print(lista.get(i) + " ");
                        g2d.setColor(Color.black);
                        g2d.draw(new Ellipse2D.Double(x, y, 50, 50));
                        g2d.fill(new Ellipse2D.Double(x, y, 50, 50));
                        g2d.drawString("P: " + (i+1), x + 15, y - 10);
                        g2d.setColor(Color.white);
                        g2d.drawString(lista.get(i) + "", x + 15, y + (50 / 2));
                    }

                    x += 60;
                    if (x >= 800) {
                        x = 150;
                        y += 60;
                    }

                }
                System.out.println("");

                break;
            case "Lista duplamente encadeada":

                break;
            case "Fila":

                break;
            case "Pilha":

                break;

        }

    }

    public void Graficar() {
        Graphics2D g2d = (Graphics2D) getGraphics();
        String figuras = jComboBox1.getSelectedItem().toString();

        switch (figuras) {
            case "Escolha a estrutura de dados":
                JOptionPane.showMessageDialog(null, "Selecione uma estrutura");
                break;
            case "Lista simplesmente encadeada":
                int x = 150;
                int y = 150;

                System.out.println("LISTA: ");
                for (int i = 0; i < lista.size(); i++) {
                    System.out.print(lista.get(i) + " ");
                    g2d.setColor(Color.black);
                    g2d.draw(new Ellipse2D.Double(x, y, 50, 50));
                    g2d.fill(new Ellipse2D.Double(x, y, 50, 50));
                    g2d.drawString("P: " + (i+1), x + 15, y - 10);
                    g2d.setColor(Color.white);
                    g2d.drawString(lista.get(i) + "", x + 15, y + (50 / 2));

                    x += 60;
                    if (x >= 800) {
                        x = 150;
                        y += 60;
                    }

                }
                System.out.println("");

                break;
            case "Lista duplamente encadeada":

                break;
            case "Fila":

                break;
            case "Pilha":

                break;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a estrutura de dados", "Lista simplesmente encadeada", "Lista duplamente encadeada", "Pilha", "Fila", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Retirar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Busca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)
                        .addGap(222, 222, 222)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String figuras2;
        figuras2 = jComboBox1.getSelectedItem().toString();
        switch (figuras2) {
            case "Escolha a estrutura de dados":
                JOptionPane.showMessageDialog(null, "Seleciona uma figura");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField1.setVisible(false);
                jTextField2.setVisible(false);
                break;

            case "Lista simplesmente encadeada":
                jLabel1.setText("Valor");
                jLabel2.setText("Posição");
                jTextField1.setEditable(true);
                jTextField2.setEditable(true);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField2.setVisible(true);
                break;

            case "Lista duplamente encadeada":
                jLabel1.setText("Valor");
                jLabel2.setText("Posição");
                jTextField1.setEditable(true);
                jTextField2.setEditable(true);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField2.setVisible(true);
                break;

            case "Pilha":
                jLabel1.setText("Valor");
                jLabel2.setText("");
                jTextField1.setEditable(true);
                jTextField2.setEditable(false);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField2.setVisible(false);
                break;

            case "Fila":
                jLabel1.setText("Valor");
                jLabel2.setText("");
                jTextField1.setEditable(true);
                jTextField2.setEditable(false);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField2.setVisible(false);
                break;

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
            JOptionPane.showInputDialog(null, "Digite todos os campos");
            jTextField1.requestFocus();
        } else {
            lista.add(Integer.parseInt(jTextField2.getText())-1, Integer.parseInt(jTextField1.getText()));
            jTextField1.setText("");
            jTextField2.setText("");
            Graficar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Graphics g = getGraphics();
        super.paint(g);

        if (jTextField2.getText().equals("")) {
            JOptionPane.showInputDialog(null, "ENTREI AQUI");
            jTextField1.requestFocus();
        } else {
            String figuras = jComboBox1.getSelectedItem().toString();

            switch (figuras) {
                case "Escolha a estrutura de dados":
                    JOptionPane.showMessageDialog(null, "Selecione uma estrutura");
                    break;
                case "Lista simplesmente encadeada":
                    lista.remove(Integer.parseInt(jTextField2.getText())-1);
                    Graficar();
                    break;
                case "Lista duplamente encadeada":

                    break;
                case "Fila":

                    break;
                case "Pilha":

                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int valor = Integer.parseInt(jTextField1.getText());
        int pos = -1;

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i) == valor) {
                pos = lista.indexOf(i);
                break;

            }
        }
        
        if(pos > -1){
            Graphics g = getGraphics();
            super.paint(g);
            Graficar(pos);
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DibujaPrimitivasFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DibujaPrimitivasFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DibujaPrimitivasFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DibujaPrimitivasFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DibujaPrimitivasFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
